./spl ../stage17/os_startup.spl
echo "Successful"
./spl ../stage17/scheduler_module.spl
echo "Successful"
./spl ../stage17/boot_module.spl
echo "Successful"
./spl ../stage17/sample_int7.spl
echo "Successful"
./spl ../stage17/sample_timer.spl
echo "Successful"
./spl ../stage17/int10.spl
echo "Successful"
./spl ../stage17/module_0.spl
echo "Successful"
./spl ../stage17/module_1.spl
echo "Successful"
./spl ../stage17/module_2.spl
echo "Successful"
./spl ../stage17/module_4.spl
echo "Successful"
./spl ../stage17/sample_int6.spl
echo "Successful"
./spl ../stage17/console_interrupt.spl
echo "Successful"
./spl ../stage17/sample_int9.spl
echo "Successful"