./spl ../stage20/os_startup.spl
echo "Successful"
./spl ../stage20/scheduler_module.spl
echo "Successful"
./spl ../stage20/boot_module.spl
echo "Successful"
./spl ../stage20/sample_int7.spl
echo "Successful"
./spl ../stage20/sample_timer.spl
echo "Successful"
./spl ../stage20/int10.spl
echo "Successful"
./spl ../stage20/module_0.spl
echo "Successful"
./spl ../stage20/module_1.spl
echo "Successful"
./spl ../stage20/module_2.spl
echo "Successful"
./spl ../stage20/module_4.spl
echo "Successful"
./spl ../stage20/sample_int6.spl
echo "Successful"
./spl ../stage20/console_interrupt.spl
echo "Successful"
./spl ../stage20/sample_int9.spl
echo "Successful"
./spl ../stage20/disk_interrupt.spl
echo "Successful"
./spl ../stage20/exhandler.spl
echo "Successful"
./spl ../stage20/sample_int8.spl
echo "Successful"