./spl ../stage24/os_startup.spl
echo "Successful1"
./spl ../stage24/scheduler_module.spl
echo "Successful2"
./spl ../stage24/boot_module.spl
echo "Successful3"
./spl ../stage24/sample_int7.spl
echo "Successful4"
./spl ../stage24/sample_timer.spl
echo "Successful5"
./spl ../stage24/int10.spl
echo "Successful6"
./spl ../stage24/module_0.spl
echo "Successful7"
./spl ../stage24/module_1.spl
echo "Successful8"
./spl ../stage24/module_2.spl
echo "Successful9"
./spl ../stage24/module_4.spl
echo "Successful10"
./spl ../stage24/int6_mod.spl
echo "Successful11"
./spl ../stage24/console_interrupt.spl
echo "Successful12"
./spl ../stage24/sample_int9.spl
echo "Successful13"
./spl ../stage24/disk_interrupt.spl
echo "Successful14"
./spl ../stage24/exhandler.spl
echo "Successful15"
./spl ../stage24/sample_int8.spl
echo "Successful16"
./spl ../stage24/sample_int11.spl
echo "Successful17"
./spl ../stage24/sample_int15.spl
echo "Successful18"
./spl ../stage24/sample_int13_copy.spl
echo "Successful19"
./spl ../stage24/sample_int14_copy.spl
echo "Successful20"
./spl ../stage24/sample_int4.spl
echo "Successful21"
./spl ../stage24/module_3.spl
echo "Successful22"
./spl ../stage24/sample_int5.spl
echo "Successful23"
