./spl ../stage21/os_startup.spl
echo "Successful"
./spl ../stage21/scheduler_module.spl
echo "Successful"
./spl ../stage21/boot_module.spl
echo "Successful"
./spl ../stage21/sample_int7.spl
echo "Successful"
./spl ../stage21/sample_timer.spl
echo "Successful"
./spl ../stage21/int10.spl
echo "Successful"
./spl ../stage21/module_0.spl
echo "Successful"
./spl ../stage21/module_1.spl
echo "Successful"
./spl ../stage21/module_2.spl
echo "Successful"
./spl ../stage21/module_4.spl
echo "Successful"
./spl ../stage21/sample_int6.spl
echo "Successful"
./spl ../stage21/console_interrupt.spl
echo "Successful"
./spl ../stage21/sample_int9.spl
echo "Successful"
./spl ../stage21/disk_interrupt.spl
echo "Successful"
./spl ../stage21/exhandler.spl
echo "Successful"
./spl ../stage21/sample_int8.spl
echo "Successful"
./spl ../stage21/sample_int11.spl
echo "Successful"
./spl ../stage21/sample_int15.spl
