./spl ../stage18/os_startup.spl
echo "Successful"
./spl ../stage18/scheduler_module.spl
echo "Successful"
./spl ../stage18/boot_module.spl
echo "Successful"
./spl ../stage18/sample_int7.spl
echo "Successful"
./spl ../stage18/sample_timer.spl
echo "Successful"
./spl ../stage18/int10.spl
echo "Successful"
./spl ../stage18/module_0.spl
echo "Successful"
./spl ../stage18/module_1.spl
echo "Successful"
./spl ../stage18/module_2.spl
echo "Successful"
./spl ../stage18/module_4.spl
echo "Successful"
./spl ../stage18/sample_int6.spl
echo "Successful"
./spl ../stage18/console_interrupt.spl
echo "Successful"
./spl ../stage18/sample_int9.spl
echo "Successful"
./spl ../stage18/disk_interrupt.spl
echo "Successful"

