./spl ../stage19/os_startup.spl
echo "Successful1"
./spl ../stage19/scheduler_module.spl
echo "Successful2"
./spl ../stage19/boot_module.spl
echo "Successful3"
./spl ../stage19/sample_int7.spl
echo "Successful4"
./spl ../stage19/sample_timer.spl
echo "Successful5"
./spl ../stage19/int10.spl
echo "Successful6"
./spl ../stage19/module_0.spl
echo "Successful7"
./spl ../stage19/module_1.spl
echo "Successful8"
./spl ../stage19/module_2.spl
echo "Successful9"
./spl ../stage19/module_4.spl
echo "Successful10"
./spl ../stage19/sample_int6.spl
echo "Successful11"
./spl ../stage19/console_interrupt.spl
echo "Successful12"
./spl ../stage19/sample_int9.spl
echo "Successful13"
./spl ../stage19/disk_interrupt.spl
echo "Successful14"
./spl ../stage19/exhandler.spl
echo "Successful15"
