./spl ../stage19/os_startup.spl
echo "Successful"
./spl ../stage19/scheduler_module.spl
echo "Successful"
./spl ../stage19/boot_module.spl
echo "Successful"
./spl ../stage19/sample_int7.spl
echo "Successful"
./spl ../stage19/sample_timer.spl
echo "Successful"
./spl ../stage19/int10.spl
echo "Successful"
./spl ../stage19/module_0.spl
echo "Successful"
./spl ../stage19/module_1.spl
echo "Successful"
./spl ../stage19/module_2.spl
echo "Successful"
./spl ../stage19/module_4.spl
echo "Successful"
./spl ../stage19/sample_int6.spl
echo "Successful"
./spl ../stage19/console_interrupt.spl
echo "Successful"
./spl ../stage19/sample_int9.spl
echo "Successful"
./spl ../stage19/disk_interrupt.spl
echo "Successful"
./spl ../stage19/exhandler.spl
echo "Successful"