./spl ../stage22/os_startup.spl
echo "Successful"
./spl ../stage22/scheduler_module.spl
echo "Successful"
./spl ../stage22/boot_module.spl
echo "Successful"
./spl ../stage22/sample_int7.spl
echo "Successful"
./spl ../stage22/sample_timer.spl
echo "Successful"
./spl ../stage22/int10.spl
echo "Successful"
./spl ../stage22/module_0.spl
echo "Successful"
./spl ../stage22/module_1.spl
echo "Successful"
./spl ../stage22/module_2.spl
echo "Successful"
./spl ../stage22/module_4.spl
echo "Successful"
./spl ../stage22/sample_int6.spl
echo "Successful"
./spl ../stage22/console_interrupt.spl
echo "Successful"
./spl ../stage22/sample_int9.spl
echo "Successful"
./spl ../stage22/disk_interrupt.spl
echo "Successful"
./spl ../stage22/exhandler.spl
echo "Successful"
./spl ../stage22/sample_int8.spl
echo "Successful"
./spl ../stage22/sample_int11.spl
echo "Successful"
./spl ../stage22/sample_int15.spl
echo "Successful"
./spl ../stage22/sample_int13.spl
echo "Successful"
./spl ../stage22/sample_int14.spl
