./spl ../stage23/os_startup.spl
echo "Successful1"
./spl ../stage23/scheduler_module.spl
echo "Successful2"
./spl ../stage23/boot_module.spl
echo "Successful3"
./spl ../stage23/sample_int7.spl
echo "Successful4"
./spl ../stage23/sample_timer.spl
echo "Successful5"
./spl ../stage23/int10.spl
echo "Successful6"
./spl ../stage23/module_0.spl
echo "Successful7"
./spl ../stage23/module_1.spl
echo "Successful8"
./spl ../stage23/module_2.spl
echo "Successful9"
./spl ../stage23/module_4.spl
echo "Successful10"
./spl ../stage23/sample_int6.spl
echo "Successful11"
./spl ../stage23/console_interrupt.spl
echo "Successful12"
./spl ../stage23/sample_int9.spl
echo "Successful13"
./spl ../stage23/disk_interrupt.spl
echo "Successful14"
./spl ../stage23/exhandler.spl
echo "Successful15"
./spl ../stage23/sample_int8.spl
echo "Successful16"
./spl ../stage23/sample_int11.spl
echo "Successful17"
./spl ../stage23/sample_int15.spl
echo "Successful18"
./spl ../stage23/sample_int13_copy.spl
echo "Successful19"
./spl ../stage23/sample_int14_copy.spl
echo "Successful20"
./spl ../stage23/sample_int4.spl
echo "Successful21"
